# Generated by Django 2.1.5 on 2019-03-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrelation',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注文日時'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='利用開始'),
        ),
    ]
