# Generated by Django 2.1.5 on 2019-03-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0004_auto_20190320_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='market',
            field=models.CharField(default='bitbank', max_length=50, verbose_name='取引所'),
        ),
    ]
