# Generated by Django 2.1.5 on 2019-03-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0006_auto_20190321_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrelation',
            name='user',
        ),
    ]
