# Generated by Django 2.1.5 on 2019-03-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0008_orderrelation_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BitbankOrder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderRelation',
            new_name='Relation',
        ),
    ]
