# Generated by Django 2.1.5 on 2019-03-21 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0009_auto_20190321_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trail_width',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='トレール幅'),
        ),
    ]
