# Generated by Django 2.1.5 on 2019-03-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0011_order_trail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='market',
            field=models.CharField(default='bitbank', max_length=50, verbose_name='取引所'),
        ),
    ]
