# Generated by Django 2.1.5 on 2019-03-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0012_relation_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='api_secret_key',
        ),
        migrations.AddField(
            model_name='user',
            name='bb_api_key',
            field=models.CharField(default='fake', max_length=255, verbose_name='BITBANK API KEY'),
        ),
        migrations.AddField(
            model_name='user',
            name='bb_api_secret_key',
            field=models.CharField(default='fake', max_length=255, verbose_name='BITBANK API SECRET KEY'),
        ),
        migrations.AddField(
            model_name='user',
            name='cc_api_key',
            field=models.CharField(default='fake', max_length=255, verbose_name='COINCHECK API KEY'),
        ),
        migrations.AddField(
            model_name='user',
            name='cc_api_secret_key',
            field=models.CharField(default='fake', max_length=255, null=True, verbose_name='COINCHECK API SECRET KEY'),
        ),
    ]
