# Generated by Django 2.1.5 on 2019-03-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0013_auto_20190323_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cc_api_secret_key',
            field=models.CharField(default='fake', max_length=255, verbose_name='COINCHECK API SECRET KEY'),
        ),
    ]
