# Generated by Django 2.1.5 on 2019-03-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0015_auto_20190324_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bb_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='bitbank API KEY'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bb_api_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='bitbank API SECRET KEY'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cc_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='coincheck API KEY'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cc_api_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='coincheck API SECRET KEY'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_for_notice',
            field=models.EmailField(max_length=254, verbose_name='通知用メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='名前'),
        ),
    ]
