# Generated by Django 2.1.5 on 2019-03-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0019_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
