# Generated by Django 2.1.5 on 2019-04-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0020_delete_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': '通知設定', 'verbose_name_plural': '4.通知設定'},
        ),
        migrations.AlterModelOptions(
            name='bankinfo',
            options={'verbose_name': '口座情報', 'verbose_name_plural': '6.口座情報'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': '問い合せ', 'verbose_name_plural': '5.問い合せ'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '取引履歴', 'verbose_name_plural': '3.取引履歴'},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name': '発注一覧', 'verbose_name_plural': '2.発注一覧'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '利用者', 'verbose_name_plural': '1.利用者'},
        ),
    ]
