# Generated by Django 2.1.5 on 2019-07-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0022_bankinfo_meigi'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='ロック中'),
        ),
    ]
