# Generated by Django 2.1.5 on 2019-07-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0023_relation_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='comment',
            field=models.CharField(default='', max_length=255, verbose_name='コメント'),
        ),
    ]
